[project]
name = "backend"
version = "0.1.0"
description = "backend for tubeify"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.12",
    "pytube>=15.0.0",
    "uvicorn>=0.34.0",
    "yt-dlp>=2025.3.27",
]

